ALTER TABLE equipment ADD COLUMN IF NOT EXISTS qr_broken BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE equipment ADD COLUMN IF NOT EXISTS written_off_at TIMESTAMPTZ;
ALTER TABLE equipment ADD COLUMN IF NOT EXISTS write_off_reason TEXT NOT NULL DEFAULT '';
